name: Release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      label:
        description: 'Label'
        type: string
        required: true

jobs:
  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Create temporary branch
        run: git checkout -b temp
      - name: Install Node.js
        uses: volta-cli/action@v1
      - name: Install dependencies
        run: npm ci
      - name: Build release
        run: npm run build
      - name: Sanitize release
        run: node ./lib/utilities/sanitizeRelease.mjs
      - name: Initialize git config
        run: |
          git config user.name "Github Actions"
          git config user.email noreply@github.com
      - name: Stash changes
        run: |
          git add .
          git stash
      - name: Configure release branch
        run: |
          git checkout -b release
          git fetch origin release
          git branch --set-upstream-to=origin/release release
          git pull --no-rebase
      - name: Commit changes
        run: |
          git stash pop
          git add .
          git commit -m "Update release ${{ steps.date.outputs.date }}"
      - name: Push updates
        run: git push
