name: Release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      label:
        description: 'Label'
        type: string
        required: true

jobs:
  prepare_release:
    name: Prepare release
    runs-on: ubuntu-latest

    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Create temporary branch
        run: git checkout -b temp
      - name: Install Node.js
        uses: volta-cli/action@v1
      - name: Install dependencies
        run: npm ci
      - name: Build release
        run: npm run build
      - name: Sanitize release
        run: node ./lib/utilities/sanitizeRelease.mjs
      - name: Initialize git config
        run: |
          git config user.name "Github Actions"
          git config user.email noreply@github.com
      - name: Commit changes
        run: |
          git add .
          git commit -m "Update release ${{ github.event.repository.updated_at}}"
      - name: Configure release branch
        run: |
          git pull origin release
          git branch --set-upstream-to=origin/release temp
      - name: Push updates
        run: git push
